language: php
dist: precise

php:
    - 5.6
    - 7.0
    - 7.1

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer install

script:
  - vendor/bin/phpunit --bootstrap vendor/autoload.php --coverage-text --coverage-clover=coverage.clover